"""
SANS Institute course number -> full name.
Used to auto-fill course name when the operator enters a known course number.
Source: sans.org/cyber-security-courses (85 courses as of Feb 2026).
"""

SANS_COURSES = {
    # --- AIS (AI Security) ---
    "AIS247": "AI Security Essentials for Business Leaders",
    # --- SEC (Security) ---
    "SEC275": "Foundations: Computers, Technology, & Security",
    "SEC301": "Introduction to Cyber Security",
    "SEC366": "CIS Implementation Group 1",
    "SEC401": "Security Essentials - Network, Endpoint, and Cloud",
    "SEC402": "Cybersecurity Writing: Hack the Reader",
    "SEC403": "Secrets to Successful Cybersecurity Presentation",
    "SEC405": "Business Finance Essentials",
    "SEC411": "AI Security Principles and Practices: GenAI and LLM Defense",
    "SEC450": "SOC Analyst Training - Applied Skills for Cyber Defense Operations",
    "SEC480": "AWS Secure Builder",
    "SEC495": "Leveraging LLMs: Building & Securing RAG, Contextual RAG, and Agentic RAG",
    "SEC497": "Practical Open-Source Intelligence (OSINT)",
    "SEC501": "Advanced Security Essentials - Enterprise Defender",
    "SEC502": "Cloud Security Tactical Defense",
    "SEC503": "Network Monitoring and Threat Detection In-Depth",
    "SEC504": "Hacker Tools, Techniques, and Incident Handling",
    "SEC506": "Securing Linux/Unix",
    "SEC510": "Cloud Security Engineering and Controls",
    "SEC511": "Cybersecurity Engineering: Advanced Threat Detection and Monitoring",
    "SEC522": "Application Security: Securing Web Applications, APIs, and Microservices",
    "SEC529": "Quantum Security Readiness for Executives",
    "SEC530": "Defensible Security Architecture and Engineering: Implementing Zero Trust for the Hybrid Enterprise",
    "SEC535": "Offensive AI - Attack Tools and Techniques",
    "SEC540": "Cloud Native Security and DevSecOps Automation",
    "SEC541": "Cloud Security Threat Detection",
    "SEC542": "Web App Penetration Testing and Ethical Hacking",
    "SEC545": "GenAI and LLM Application Security",
    "SEC549": "Cloud Security Architecture",
    "SEC555": "Detection Engineering and SIEM Analytics",
    "SEC556": "IoT Penetration Testing",
    "SEC559": "Cloud and Hybrid Identity Security",
    "SEC560": "Enterprise Penetration Testing",
    "SEC565": "Red Team Operations and Adversary Emulation",
    "SEC566": "Implementing and Auditing CIS Controls",
    "SEC573": "AI-Powered Security Automation: Building Tools with Python, LLMs, and MCP",
    "SEC575": "iOS and Android Application Security Analysis and Penetration Testing",
    "SEC580": "Metasploit for Enterprise Penetration Testing",
    "SEC587": "Advanced Open-Source Intelligence (OSINT) Gathering and Analysis",
    "SEC588": "Cloud Penetration Testing",
    "SEC595": "Applied Data Science and AI/Machine Learning for Cybersecurity Professionals",
    "SEC598": "AI and Security Automation for Red, Blue, and Purple Teams",
    "SEC599": "Defeating Advanced Adversaries - Purple Team Tactics & Kill Chain Defenses",
    "SEC617": "Wireless Penetration Testing and Ethical Hacking",
    "SEC660": "Advanced Penetration Testing, Exploit Writing, and Ethical Hacking",
    "SEC665": "Advanced Red Team Operations",
    "SEC670": "Red Teaming Tools - Developing Windows Implants, Shellcode, Command and Control",
    "SEC673": "Advanced Information Security Automation with Python",
    "SEC699": "Advanced Purple Teaming - Adversary Emulation & Detection Engineering",
    "SEC760": "Advanced Exploit Development for Penetration Testers",
    # --- FOR (Forensics & Incident Response) ---
    "FOR498": "Digital Acquisition and Rapid Triage",
    "FOR500": "Windows Forensic Analysis",
    "FOR508": "Advanced Incident Response, Threat Hunting, and Digital Forensics",
    "FOR509": "Enterprise Cloud Forensics and Incident Response",
    "FOR518": "Mac and iOS Forensic Analysis and Incident Response",
    "FOR528": "Ransomware and Cyber Extortion",
    "FOR563": "Applied AI for Digital Forensics and Incident Response: Leveraging Local Large Language Models",
    "FOR572": "Advanced Network Forensics: Threat Hunting, Analysis, and Incident Response",
    "FOR577": "LINUX Incident Response and Threat Hunting",
    "FOR578": "Cyber Threat Intelligence",
    "FOR585": "Smartphone Forensic Analysis In-Depth",
    "FOR589": "Cybercrime Investigations",
    "FOR608": "Enterprise-Class Incident Response & Threat Hunting",
    "FOR610": "Reverse-Engineering Malware: Malware Analysis Tools and Techniques",
    "FOR710": "Reverse-Engineering Malware: Advanced Code Analysis",
    # --- ICS (Industrial Control Systems) ---
    "ICS310": "ICS Cybersecurity Foundations",
    "ICS410": "ICS/SCADA Security Essentials",
    "ICS418": "ICS Security Essentials for Leaders",
    "ICS456": "Essentials for NERC Critical Infrastructure Protection",
    "ICS515": "ICS Visibility, Detection, and Response",
    "ICS612": "ICS Cybersecurity In-Depth",
    "ICS613": "ICS/OT Penetration Testing & Assessments",
    # --- LDR (Leadership) ---
    "LDR414": "SANS Training Program for CISSP Certification",
    "LDR419": "Performing A Cybersecurity Risk Assessment",
    "LDR433": "Managing Human Risk",
    "LDR512": "Security Leadership Essentials for Managers",
    "LDR514": "Security Strategic Planning, Policy, and Leadership",
    "LDR516": "Strategic Vulnerability and Threat Management",
    "LDR519": "Cybersecurity Risk Management and Compliance",
    "LDR520": "Emerging Trends for Cyber Leaders: AI and Cloud",
    "LDR521": "Security Culture for Leaders",
    "LDR551": "Building and Leading Security Operations Centers",
    "LDR553": "Cyber Incident Management",
}
